INSERT INTO avis (id,zap,message) VALUES (1,"kml_32","auctor velit. Aliquam nisl. Nulla");
INSERT INTO avis (id,zap,message) VALUES (2,"kml_51","libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus");
INSERT INTO avis (id,zap,message) VALUES (3,"kml_56","nisi. Aenean eget metus. In nec orci. Donec nibh.");
INSERT INTO avis (id,zap,message) VALUES (4,"kml_21","nunc. Quisque ornare tortor at risus. Nunc ac sem ut");
INSERT INTO avis (id,zap,message) VALUES (5,"kml_39","elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor");
INSERT INTO avis (id,zap,message) VALUES (6,"kml_57","lorem");
INSERT INTO avis (id,zap,message) VALUES (7,"kml_8","ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper");
INSERT INTO avis (id,zap,message) VALUES (8,"kml_3","vulputate velit eu sem.");
INSERT INTO avis (id,zap,message) VALUES (9,"kml_31","metus. Vivamus euismod urna.");
INSERT INTO avis (id,zap,message) VALUES (10,"kml_51","purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna,");
INSERT INTO avis (id,zap,message) VALUES (11,"kml_13","sed");
INSERT INTO avis (id,zap,message) VALUES (12,"kml_56","Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum");
INSERT INTO avis (id,zap,message) VALUES (13,"kml_30","et malesuada fames ac turpis egestas. Fusce aliquet magna a neque.");
INSERT INTO avis (id,zap,message) VALUES (14,"kml_12","vel, mauris.");
INSERT INTO avis (id,zap,message) VALUES (15,"kml_11","quam, elementum at,");
INSERT INTO avis (id,zap,message) VALUES (16,"kml_8","mauris sapien, cursus");
INSERT INTO avis (id,zap,message) VALUES (17,"kml_1","lacinia");
INSERT INTO avis (id,zap,message) VALUES (18,"kml_16","sit amet");
INSERT INTO avis (id,zap,message) VALUES (19,"kml_24","consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut,");
INSERT INTO avis (id,zap,message) VALUES (20,"kml_1","Donec nibh. Quisque nonummy ipsum");
INSERT INTO avis (id,zap,message) VALUES (21,"kml_57","dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu");
INSERT INTO avis (id,zap,message) VALUES (22,"kml_17","ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse");
INSERT INTO avis (id,zap,message) VALUES (23,"kml_2","magna. Nam ligula elit, pretium et, rutrum non, hendrerit");
INSERT INTO avis (id,zap,message) VALUES (24,"kml_10","sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus");
INSERT INTO avis (id,zap,message) VALUES (25,"kml_31","magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient");
INSERT INTO avis (id,zap,message) VALUES (26,"kml_21","gravida molestie arcu. Sed eu");
INSERT INTO avis (id,zap,message) VALUES (27,"kml_42","Praesent eu dui. Cum sociis natoque penatibus et magnis");
INSERT INTO avis (id,zap,message) VALUES (28,"kml_17","lacus pede sagittis augue, eu tempor erat");
INSERT INTO avis (id,zap,message) VALUES (29,"kml_47","ornare, lectus ante dictum");
INSERT INTO avis (id,zap,message) VALUES (30,"kml_53","Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.");
INSERT INTO avis (id,zap,message) VALUES (31,"kml_50","Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla");
INSERT INTO avis (id,zap,message) VALUES (32,"kml_1","tempus risus. Donec");
INSERT INTO avis (id,zap,message) VALUES (33,"kml_39","Quisque libero");
INSERT INTO avis (id,zap,message) VALUES (34,"kml_19","In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac");
INSERT INTO avis (id,zap,message) VALUES (35,"kml_39","et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus");
INSERT INTO avis (id,zap,message) VALUES (36,"kml_26","Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia");
INSERT INTO avis (id,zap,message) VALUES (37,"kml_22","molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed");
INSERT INTO avis (id,zap,message) VALUES (38,"kml_14","dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque");
INSERT INTO avis (id,zap,message) VALUES (39,"kml_34","quis lectus. Nullam suscipit,");
INSERT INTO avis (id,zap,message) VALUES (40,"kml_12","consequat enim diam vel");
INSERT INTO avis (id,zap,message) VALUES (41,"kml_57","lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,");
INSERT INTO avis (id,zap,message) VALUES (42,"kml_11","ac mattis");
INSERT INTO avis (id,zap,message) VALUES (43,"kml_4","tellus, imperdiet non, vestibulum");
INSERT INTO avis (id,zap,message) VALUES (44,"kml_9","porttitor vulputate, posuere vulputate, lacus.");
INSERT INTO avis (id,zap,message) VALUES (45,"kml_57","odio tristique pharetra. Quisque ac libero nec");
INSERT INTO avis (id,zap,message) VALUES (46,"kml_24","Nullam nisl. Maecenas malesuada fringilla est. Mauris");
INSERT INTO avis (id,zap,message) VALUES (47,"kml_43","gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim");
INSERT INTO avis (id,zap,message) VALUES (48,"kml_18","enim");
INSERT INTO avis (id,zap,message) VALUES (49,"kml_24","eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada");
INSERT INTO avis (id,zap,message) VALUES (50,"kml_1","Cras dolor dolor,");
INSERT INTO avis (id,zap,message) VALUES (51,"kml_9","sed");
INSERT INTO avis (id,zap,message) VALUES (52,"kml_44","dolor. Quisque tincidunt pede ac urna. Ut");
INSERT INTO avis (id,zap,message) VALUES (53,"kml_9","ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu.");
INSERT INTO avis (id,zap,message) VALUES (54,"kml_26","in, hendrerit consectetuer,");
INSERT INTO avis (id,zap,message) VALUES (55,"kml_33","Morbi quis urna. Nunc quis arcu vel");
INSERT INTO avis (id,zap,message) VALUES (56,"kml_29","sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan");
INSERT INTO avis (id,zap,message) VALUES (57,"kml_8","Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus.");
INSERT INTO avis (id,zap,message) VALUES (58,"kml_38","congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in");
INSERT INTO avis (id,zap,message) VALUES (59,"kml_3","eget metus. In nec orci. Donec nibh. Quisque");
INSERT INTO avis (id,zap,message) VALUES (60,"kml_25","erat. Etiam vestibulum massa rutrum magna. Cras convallis");
INSERT INTO avis (id,zap,message) VALUES (61,"kml_54","amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed");
INSERT INTO avis (id,zap,message) VALUES (62,"kml_50","Suspendisse non leo. Vivamus nibh dolor, nonummy ac,");
INSERT INTO avis (id,zap,message) VALUES (63,"kml_29","interdum. Curabitur dictum. Phasellus in felis. Nulla");
INSERT INTO avis (id,zap,message) VALUES (64,"kml_28","a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque");
INSERT INTO avis (id,zap,message) VALUES (65,"kml_16","sodales elit erat");
INSERT INTO avis (id,zap,message) VALUES (66,"kml_15","Mauris quis turpis");
INSERT INTO avis (id,zap,message) VALUES (67,"kml_23","blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur");
INSERT INTO avis (id,zap,message) VALUES (68,"kml_23","nec metus facilisis lorem tristique aliquet. Phasellus fermentum");
INSERT INTO avis (id,zap,message) VALUES (69,"kml_38","sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices.");
INSERT INTO avis (id,zap,message) VALUES (70,"kml_58","Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas");
INSERT INTO avis (id,zap,message) VALUES (71,"kml_37","orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer");
INSERT INTO avis (id,zap,message) VALUES (72,"kml_52","varius. Nam porttitor scelerisque neque. Nullam");
INSERT INTO avis (id,zap,message) VALUES (73,"kml_33","montes, nascetur");
INSERT INTO avis (id,zap,message) VALUES (74,"kml_21","malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet");
INSERT INTO avis (id,zap,message) VALUES (75,"kml_39","orci. Ut semper pretium neque. Morbi quis");
INSERT INTO avis (id,zap,message) VALUES (76,"kml_7","dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id,");
INSERT INTO avis (id,zap,message) VALUES (77,"kml_58","montes, nascetur ridiculus mus. Proin vel");
INSERT INTO avis (id,zap,message) VALUES (78,"kml_17","Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed");
INSERT INTO avis (id,zap,message) VALUES (79,"kml_38","massa. Integer vitae nibh. Donec est mauris, rhoncus id,");
INSERT INTO avis (id,zap,message) VALUES (80,"kml_57","purus sapien, gravida non, sollicitudin a, malesuada id,");
INSERT INTO avis (id,zap,message) VALUES (81,"kml_55","ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis");
INSERT INTO avis (id,zap,message) VALUES (82,"kml_30","accumsan laoreet ipsum.");
INSERT INTO avis (id,zap,message) VALUES (83,"kml_27","Donec");
INSERT INTO avis (id,zap,message) VALUES (84,"kml_6","Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum");
INSERT INTO avis (id,zap,message) VALUES (85,"kml_15","Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui.");
INSERT INTO avis (id,zap,message) VALUES (86,"kml_26","sagittis. Nullam vitae diam. Proin");
INSERT INTO avis (id,zap,message) VALUES (87,"kml_42","nunc sed libero. Proin sed turpis");
INSERT INTO avis (id,zap,message) VALUES (88,"kml_52","et magnis dis parturient montes, nascetur ridiculus mus. Donec");
INSERT INTO avis (id,zap,message) VALUES (89,"kml_54","pede. Nunc sed orci lobortis");
INSERT INTO avis (id,zap,message) VALUES (90,"kml_33","morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla");
INSERT INTO avis (id,zap,message) VALUES (91,"kml_20","nonummy ultricies ornare, elit");
INSERT INTO avis (id,zap,message) VALUES (92,"kml_42","mi, ac mattis");
INSERT INTO avis (id,zap,message) VALUES (93,"kml_19","arcu. Nunc mauris. Morbi non");
INSERT INTO avis (id,zap,message) VALUES (94,"kml_32","sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt");
INSERT INTO avis (id,zap,message) VALUES (95,"kml_28","vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed");
INSERT INTO avis (id,zap,message) VALUES (96,"kml_16","auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum.");
INSERT INTO avis (id,zap,message) VALUES (97,"kml_22","faucibus.");
INSERT INTO avis (id,zap,message) VALUES (98,"kml_7","diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed");
INSERT INTO avis (id,zap,message) VALUES (99,"kml_25","venenatis a, magna.");
INSERT INTO avis (id,zap,message) VALUES (100,"kml_46","tristique aliquet.");
INSERT INTO avis (id,zap,message) VALUES (101,"kml_1","leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non");
INSERT INTO avis (id,zap,message) VALUES (102,"kml_6","mattis ornare, lectus ante dictum mi, ac mattis velit");
INSERT INTO avis (id,zap,message) VALUES (103,"kml_31","felis purus ac");
INSERT INTO avis (id,zap,message) VALUES (104,"kml_12","sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie");
INSERT INTO avis (id,zap,message) VALUES (105,"kml_50","tellus justo sit");
INSERT INTO avis (id,zap,message) VALUES (106,"kml_33","nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo");
INSERT INTO avis (id,zap,message) VALUES (107,"kml_27","amet ornare lectus justo eu arcu.");
INSERT INTO avis (id,zap,message) VALUES (108,"kml_55","parturient montes, nascetur ridiculus mus. Proin vel arcu");
INSERT INTO avis (id,zap,message) VALUES (109,"kml_55","nulla. Integer vulputate,");
INSERT INTO avis (id,zap,message) VALUES (110,"kml_43","ut eros non enim commodo hendrerit. Donec");
INSERT INTO avis (id,zap,message) VALUES (111,"kml_28","mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit");
INSERT INTO avis (id,zap,message) VALUES (112,"kml_12","turpis nec mauris blandit mattis. Cras eget nisi dictum");
INSERT INTO avis (id,zap,message) VALUES (113,"kml_27","nisl. Maecenas");
INSERT INTO avis (id,zap,message) VALUES (114,"kml_21","non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum,");
INSERT INTO avis (id,zap,message) VALUES (115,"kml_5","et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem");
INSERT INTO avis (id,zap,message) VALUES (116,"kml_1","sit amet ultricies sem magna nec quam. Curabitur vel lectus.");
INSERT INTO avis (id,zap,message) VALUES (117,"kml_29","sit amet, consectetuer adipiscing elit. Etiam laoreet,");
INSERT INTO avis (id,zap,message) VALUES (118,"kml_58","Sed auctor");
INSERT INTO avis (id,zap,message) VALUES (119,"kml_45","In scelerisque scelerisque dui.");
INSERT INTO avis (id,zap,message) VALUES (120,"kml_44","Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis");
INSERT INTO avis (id,zap,message) VALUES (121,"kml_42","id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis");
INSERT INTO avis (id,zap,message) VALUES (122,"kml_36","mauris a nunc. In at");
INSERT INTO avis (id,zap,message) VALUES (123,"kml_1","Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum.");
INSERT INTO avis (id,zap,message) VALUES (124,"kml_24","amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna");
INSERT INTO avis (id,zap,message) VALUES (125,"kml_16","tincidunt,");
INSERT INTO avis (id,zap,message) VALUES (126,"kml_20","semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis");
INSERT INTO avis (id,zap,message) VALUES (127,"kml_9","magnis dis parturient montes,");
INSERT INTO avis (id,zap,message) VALUES (128,"kml_12","eget");
INSERT INTO avis (id,zap,message) VALUES (129,"kml_5","velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est.");
INSERT INTO avis (id,zap,message) VALUES (130,"kml_15","varius et, euismod");
INSERT INTO avis (id,zap,message) VALUES (131,"kml_31","mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam");
INSERT INTO avis (id,zap,message) VALUES (132,"kml_30","in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper");
INSERT INTO avis (id,zap,message) VALUES (133,"kml_54","Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie");
INSERT INTO avis (id,zap,message) VALUES (134,"kml_38","lorem eu metus.");
INSERT INTO avis (id,zap,message) VALUES (135,"kml_28","In scelerisque scelerisque dui. Suspendisse ac metus vitae");
INSERT INTO avis (id,zap,message) VALUES (136,"kml_16","massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat");
INSERT INTO avis (id,zap,message) VALUES (137,"kml_21","feugiat");
INSERT INTO avis (id,zap,message) VALUES (138,"kml_1","Nunc mauris. Morbi non sapien");
INSERT INTO avis (id,zap,message) VALUES (139,"kml_53","eleifend");
INSERT INTO avis (id,zap,message) VALUES (140,"kml_21","eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat");
INSERT INTO avis (id,zap,message) VALUES (141,"kml_5","lectus sit amet luctus vulputate, nisi");
INSERT INTO avis (id,zap,message) VALUES (142,"kml_31","eget, dictum placerat, augue. Sed molestie. Sed id risus");
INSERT INTO avis (id,zap,message) VALUES (143,"kml_58","blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu,");
INSERT INTO avis (id,zap,message) VALUES (144,"kml_8","taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.");
INSERT INTO avis (id,zap,message) VALUES (145,"kml_20","Nunc commodo auctor velit. Aliquam nisl. Nulla eu");
INSERT INTO avis (id,zap,message) VALUES (146,"kml_22","libero mauris, aliquam eu, accumsan sed, facilisis");
INSERT INTO avis (id,zap,message) VALUES (147,"kml_15","Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed");
INSERT INTO avis (id,zap,message) VALUES (148,"kml_22","egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt");
INSERT INTO avis (id,zap,message) VALUES (149,"kml_56","auctor, nunc nulla vulputate dui, nec tempus mauris erat eget");
INSERT INTO avis (id,zap,message) VALUES (150,"kml_5","eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit");
INSERT INTO avis (id,zap,message) VALUES (151,"kml_17","a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam");
INSERT INTO avis (id,zap,message) VALUES (152,"kml_1","Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis.");
INSERT INTO avis (id,zap,message) VALUES (153,"kml_18","est. Mauris eu turpis.");
INSERT INTO avis (id,zap,message) VALUES (154,"kml_57","imperdiet, erat nonummy ultricies ornare,");
INSERT INTO avis (id,zap,message) VALUES (155,"kml_47","mauris.");
INSERT INTO avis (id,zap,message) VALUES (156,"kml_19","cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna,");
INSERT INTO avis (id,zap,message) VALUES (157,"kml_5","pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce");
INSERT INTO avis (id,zap,message) VALUES (158,"kml_57","a odio semper cursus.");
INSERT INTO avis (id,zap,message) VALUES (159,"kml_5","Nulla semper tellus");
INSERT INTO avis (id,zap,message) VALUES (160,"kml_9","pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu");
INSERT INTO avis (id,zap,message) VALUES (161,"kml_35","enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent");
INSERT INTO avis (id,zap,message) VALUES (162,"kml_39","tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget");
INSERT INTO avis (id,zap,message) VALUES (163,"kml_36","ac ipsum. Phasellus vitae");
INSERT INTO avis (id,zap,message) VALUES (164,"kml_39","natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec");
INSERT INTO avis (id,zap,message) VALUES (165,"kml_13","elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui");
INSERT INTO avis (id,zap,message) VALUES (166,"kml_31","ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta");
INSERT INTO avis (id,zap,message) VALUES (167,"kml_33","habitant morbi tristique senectus et netus et malesuada fames");
INSERT INTO avis (id,zap,message) VALUES (168,"kml_52","consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia");
INSERT INTO avis (id,zap,message) VALUES (169,"kml_30","Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer");
INSERT INTO avis (id,zap,message) VALUES (170,"kml_33","Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet,");
INSERT INTO avis (id,zap,message) VALUES (171,"kml_50","purus, in molestie tortor nibh sit");
INSERT INTO avis (id,zap,message) VALUES (172,"kml_27","Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est");
INSERT INTO avis (id,zap,message) VALUES (173,"kml_21","aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem");
INSERT INTO avis (id,zap,message) VALUES (174,"kml_21","consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing");
INSERT INTO avis (id,zap,message) VALUES (175,"kml_52","elit erat vitae risus. Duis");
INSERT INTO avis (id,zap,message) VALUES (176,"kml_25","eu arcu. Morbi sit amet massa.");
INSERT INTO avis (id,zap,message) VALUES (177,"kml_19","gravida sit amet, dapibus id, blandit at,");
INSERT INTO avis (id,zap,message) VALUES (178,"kml_9","Cras convallis convallis dolor. Quisque tincidunt pede ac");
INSERT INTO avis (id,zap,message) VALUES (179,"kml_13","Ut");
INSERT INTO avis (id,zap,message) VALUES (180,"kml_30","odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut,");
INSERT INTO avis (id,zap,message) VALUES (181,"kml_31","Duis risus");
INSERT INTO avis (id,zap,message) VALUES (182,"kml_5","Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec");
INSERT INTO avis (id,zap,message) VALUES (183,"kml_38","sem. Nulla interdum. Curabitur dictum. Phasellus in");
INSERT INTO avis (id,zap,message) VALUES (184,"kml_14","eleifend non, dapibus");
INSERT INTO avis (id,zap,message) VALUES (185,"kml_30","ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes,");
INSERT INTO avis (id,zap,message) VALUES (186,"kml_58","mollis non, cursus non, egestas a, dui.");
INSERT INTO avis (id,zap,message) VALUES (187,"kml_21","Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget");
INSERT INTO avis (id,zap,message) VALUES (188,"kml_19","bibendum");
INSERT INTO avis (id,zap,message) VALUES (189,"kml_19","elementum,");
INSERT INTO avis (id,zap,message) VALUES (190,"kml_32","dolor. Fusce mi lorem, vehicula");
INSERT INTO avis (id,zap,message) VALUES (191,"kml_19","sagittis placerat. Cras");
INSERT INTO avis (id,zap,message) VALUES (192,"kml_10","Aliquam auctor, velit");
INSERT INTO avis (id,zap,message) VALUES (193,"kml_21","enim. Mauris quis turpis vitae");
INSERT INTO avis (id,zap,message) VALUES (194,"kml_2","enim. Mauris quis turpis");
INSERT INTO avis (id,zap,message) VALUES (195,"kml_10","elementum sem, vitae aliquam eros turpis");
INSERT INTO avis (id,zap,message) VALUES (196,"kml_10","Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit");
INSERT INTO avis (id,zap,message) VALUES (197,"kml_28","quam. Curabitur vel lectus. Cum sociis natoque penatibus et");
INSERT INTO avis (id,zap,message) VALUES (198,"kml_7","dictum eu, placerat eget, venenatis a, magna.");
INSERT INTO avis (id,zap,message) VALUES (199,"kml_4","dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas");
INSERT INTO avis (id,zap,message) VALUES (200,"kml_7","pede, malesuada vel, venenatis");
